CxList methods = Find_Methods();

List<string> methodsNames = new List<string>{
		"calloc","chown","gets","getpwuid","malloc",
		"memalign","mkstemp","readlink","realloc",
		"RegOpenKey","RegQueryValue","sprintf","strtok",
		"tmpnam","tmpnam_r","tmpfile","remove","valloc",
		"__wcserror_s","_cgets_s","_cgetws_s","_chsize_s",
		"_controlfp_s","_cprintf_s","_cscanf_s","_cscanf_s_l",
		"_ctime32_s","_ctime64_s","_cwscanf_s","_cwscanf_s_l",
		"_ecvt_s","_fcvt_s","_fscanf_s_l","_fwscanf_s_l","_gcvt_s",
		"_getws_s","_gmtime_s","_gmtime32_s","_gmtime64_s","_i64toa_s",
		"_i64tow_s","_itoa_s","_itow_s","_lfind_s","_localtime_s",
		"_localtime32_s","_localtime64_s","_lsearch_s","_ltoa_s",
		"_ltow_s","_mbccpy_s","_mbccpy_s_l","_mbscat_s","_mbscpy_s",
		"_mbslwr_s","_mbslwr_s_l","_mbsnbcat_s","_mbsnbcat_s_l",
		"_mbsnbcpy_s","_mbsnbcpy_s_l","_mbsnbset_s","_mbsnbset_s_l",
		"_mbsncat_s","_mbsncat_s_l","_mbsncpy_s","_mbsncpy_s_l",
		"_mbsnset_s","_mbsnset_s_l","_mbsset_s","_mbsset_s_l","_mbstok_s",
		"_mbstok_s_l","_mbstowcs_s_l","_mbsupr_s","_mbsupr_s_l",
		"_mktemp_s","_putenv_s","_scanf_s_l","_searchenv_s","_snprintf_s",
		"_snprintf","_snprintf_s_l","_snscanf_s","_snscanf_s_l","_snwprintf_s",
		"_snwprintf_s_l","_snwscanf_s","_snwscanf_s_l","_sopen_s","_splitpath_s",
		"_sprintf_s_l","_sscanf_s_l","_strdate_s","_strerror_s",
		"_strlwr_s","_strlwr_s_l","_strncat_s_l","_strncpy_s_l",
		"_strnset_s","_strnset_s_l","_strset_s","_strset_s_l",
		"_strtime_s","_strtok_s_l","_strupr_s","_strupr_s_l",
		"_swprintf_s_l","_swscanf_s_l","_ui64toa_s","_ui64tow_s",
		"_ultoa_s","_ultow_s","_umask_s","_vsnprintf_s","_vsnprintf_s_l",
		"_vsnwprintf_s","_vsnwprintf_s_l","_vsprintf_s_l","_vswprintf_s_l",
		"_wasctime_s","_wcserror_s","_wcslwr_s","_wcslwr_s_l","_wcsncat_s_l",
		"_wcsncpy_s_l","_wcsnset_s","_wcsnset_s_l","_wcsset_s","_wcsset_s_l",
		"_wcstok_s_l","_wcstombs_s_l","_wcsupr_s","_wcsupr_s_l",
		"_wctime_s","_wctime32_s","_wctime64_s","_wctomb_s_l",
		"_wfopen_s","_wfreopen_s","_wgetenv_s","_wmktemp_s",
		"_wscanf_s","_wscanf_s_l","_wsearchenv_s","_wsopen_s",
		"_wsplitpath_s","_wstrdate_s","_wstrtime_s","_wtmpnam_s",
		"asctime_s","ctime_s","fopen_s","freopen_s","fscanf_s",
		"fwscanf_s","getenv_s","gets_s","HeapAlloc","HeapCreate",
		"HeapFree","HeapReAlloc","mbsrtowcs_s","mbstowcs_s",
		"memcpy_s","memmove_s","scanf_s","snprintf","sprintf_s",
		"sscanf_s","strcat_s","strcpy_s","strerror_s","strncat_s",
		"strncpy_s","strtok_s","swprintf_s","swscanf_s","tmpfile_s",
		"vsnprintf_s","vsprintf_s","vswprintf_s","wcrtomb_s","wcscat_s",
		"wcscpy_s","wcsncat_s","wcsncpy_s","wcsrtombs_s","wcstok_s",
		"wcstombs_s","wctomb_s","wmemcpy_s","wmemmove_s","strlcpy",
		"strlcat","asprintf","vsnprintf","vasprintf","fgets"
		};

result.Add(methods.FindByShortNames(methodsNames));
result.Add(methods.FindByShortName("width") - methods.FindByMemberAccess("cin.width"));