CxList conn = Find_DB_Conn_ADOdb();
conn.Add(Find_DB_Conn_DBO()); 
conn.Add(Find_DB_Conn_Django());
conn.Add(Find_DB_Conn_Mongo());
conn.Add(Find_DB_Conn_MySQL()); 	
conn.Add(Find_DB_Conn_MSSQL()); 
conn.Add(Find_DB_Conn_ODBC());
conn.Add(Find_DB_Conn_OJDBC()); 
conn.Add(Find_DB_Conn_Oracle()); 
conn.Add(Find_DB_Conn_Peewee());		
conn.Add(Find_DB_Conn_Postgres());	
conn.Add(Find_DB_Conn_SAP());
conn.Add(Find_DB_Conn_SQLAlchemy());
conn.Add(Find_DB_Conn_SQLanywhere());
conn.Add(Find_DB_Conn_SQLite());
conn.Add(Find_DB_Conn_SqlObject());
conn.Add(Find_DB_Conn_Sybase());
conn.Add(Find_DB_Conn_DataFile());
result = conn;