result = All.FindByCustomAttribute("Controller").GetFathers().FindByType(typeof(ClassDecl));
result.Add(All.FindByCustomAttribute("RestController").GetFathers().FindByType(typeof(ClassDecl)));
result.Add(All.FindByCustomAttribute("ControllerAdvice").GetFathers().FindByType(typeof(ClassDecl)));
result.Add(All.InheritsFrom("SimpleFormController"));
result.Add(All.InheritsFrom("Controller"));
result.Add(All.InheritsFrom("AbstractWizardFormController"));
result.Add(All.InheritsFrom("SimpleControllerHandlerAdapter"));
result.Add(All.InheritsFrom("AbstractController"));
result.Add(All.InheritsFrom("AbstractCommandController"));
result.Add(All.InheritsFrom("MultiActionController"));
result.Add(All.InheritsFrom("AbstractFormController"));
result.Add(All.InheritsFrom("BaseCommandController"));
result.Add(All.InheritsFrom("CancellableFormController"));
result.Add(All.InheritsFrom("ServletWrappingController"));
result.Add(All.InheritsFrom("UrlFileNameViewController"));
result.Add(All.InheritsFrom("ServletForwardingController"));
result.Add(All.InheritsFrom("ParameterazibleViewController"));
result.Add(All.InheritsFrom("AbstractUrlViewController"));