CxList classes = Find_Class_Decl();

result = classes.InheritsFrom("Action");
result.Add(classes.InheritsFrom("DispatchActionSupport"));
result.Add(classes.InheritsFrom("ModelDriven")); 
result.Add(classes.InheritsFrom("ActionSupport")); 
result.Add(classes.InheritsFrom("LookupDispatchActionSupport")); 
result.Add(classes.InheritsFrom("MappingDispatchActionSupport"));
result.Add(classes.InheritsFrom("EventDispatchAction"));
result.Add(classes.InheritsFrom("LookupDispatchAction"));
result.Add(classes.InheritsFrom("MappingDispatchAction"));
result.Add(classes.InheritsFrom("DefinitionDispatcherAction"));
result.Add(classes.InheritsFrom("DispatchAction"));
result.Add(classes.InheritsFrom("DownloadAction"));
result.Add(classes.InheritsFrom("ForwardAction"));
result.Add(classes.InheritsFrom("IncludeAction"));
result.Add(classes.InheritsFrom("LocaleAction"));
result.Add(classes.InheritsFrom("ReloadDefinitionsAction"));
result.Add(classes.InheritsFrom("SwitchAction"));
result.Add(classes.InheritsFrom("TilesAction"));
result.Add(classes.InheritsFrom("ViewDefinitionsAction"));
result.Add(classes.InheritsFrom("DelegatingActionProxy"));
result.Add(classes.InheritsFrom("BaseAction"));
result.Add(classes.InheritsFrom("MockAction"));