// Auto Genereted

// Telerik.Windows.Controls
result.Add(All.FindByMemberAccesses(new string[]{
	"ExtendedTextBox.Text",
	"RadMaskedTextBox.Value",
	"WatermarkedTextBox.Text",
	"DistinctValuesList.SelectedItem",
	"DistinctValuesList.SelectedValue",
	"RadTreeViewItem.Header",
	"Cells.Content",
	"GridViewCell.Value",
	"GridViewCell.Content",
	"GridViewCell.GetValue", 
	"GridViewCell.SetValue",
	"GridViewCellBase.GetValue", 
	"GridViewCellBase.SetValue",
	"GridViewHeaderCell.GetValue", 
	"GridViewHeaderCell.SetValue",
	// ComponentArt
	"MaskedInput.Text", 
	"NumberInput.Value",  // numbers only
	"GridCell.Text",
	"GridCell.Value",
	"TreeViewNode.Text",
	"TreeViewNode.Value",
	"TreeViewNode.Header", 
	"Calendar.formatDate",  // Date only
	"Editor.ContentText", 
	"Editor.ContentHTML",
	"DataGridCell.Text",
	"DataGridCell.Value",
	"DataGridColumn.ColumnName",
	"DataGridGroup.Value",
	"DataGridGroup.ValueText",
	"UploadItem.FileName",
	"MenuItem.Text",
	"SItemapTableCell.Text",
	"SItemapNode.Text",
	"SItemapNode.Value",
	// Infragistics
	"GroupByAreaFieldListBox.SelectedItem",
	"GroupByAreaFieldListBox.SelectedValue",
	"CellValuePresenter.Text",
	"Cell.Value",
	"Cell.ConvertedValue",
	"CellAutomationPeer.Value",
	"IGControlBase.SetValue", 
	"IGControlBase.GetValue",
	// FarPoint
	"Cells.Text",
	"Cells.Value",
	"Cell.Text",
	"FpBoolean.CheckState",  // Boolean
	"FpCalendar.CurrentDate",
	"FpCanvas.Text",
	"FpClock.CurrentTime",
	"FpCurrency.Text",
	"FpCurrency.Value",
	"FpDateTime.Text",
	"FpDateTime.Value",
	"FpDouble.Text",
	"FpDouble.Value", 
	"FpInteger.Text",
	"FpInteger.Value",
	"FpMask.Text",
	"FpMask.Value",
	"FpPercent.Text",
	"FpPercent.Value",
	"FpSuperEdit.Text",
	"FpSuperEdit.Value",
	"FpText.Text",
	"FpText.Value"}));