CxList temp = All.FindByMemberAccess("Request.*");
CxList inputs = temp.FindByMemberAccess("Request.UserHostName");
inputs.Add(temp.FindByMemberAccess("Request.Filter"));
inputs.Add(temp.FindByMemberAccess("Request.UserHostAddress"));
inputs.Add(temp.FindByMemberAccess("Request.FilePath"));
inputs.Add(temp.FindByMemberAccess("Request.ContentEncoding"));
inputs.Add(temp.FindByMemberAccess("Request.ContentType")); 
inputs.Add(temp.FindByMemberAccess("Request.AcceptTypes"));
inputs.Add(temp.FindByMemberAccess("Request.ApplicationPath"));
inputs.Add(temp.FindByMemberAccess("Request.AppRelativeCurrentExecutionFilePath"));
inputs.Add(temp.FindByMemberAccess("Request.CurrentExecutionFilePath"));
inputs.Add(temp.FindByMemberAccess("Request.GetHashCode"));
inputs.Add(temp.FindByMemberAccess("Request.GetType"));
inputs.Add(temp.FindByMemberAccess("Request.HttpMethod"));
inputs.Add(temp.FindByMemberAccess("Request.IsAuthenticated"));
inputs.Add(temp.FindByMemberAccess("Request.IsLocal"));
inputs.Add(temp.FindByMemberAccess("Request.IsSecureConnection"));
inputs.Add(temp.FindByMemberAccess("Request.LogonUserIdentity"));
inputs.Add(temp.FindByMemberAccess("Request.MapPath"));
inputs.Add(temp.FindByMemberAccess("Request.PhysicalApplicationPath"));
inputs.Add(temp.FindByMemberAccess("Request.RequestType"));
inputs.Add(temp.FindByMemberAccess("Request.ServerVariables"));
inputs.Add(temp.FindByMemberAccess("Request.ValidateInput"));

temp = All.FindByMemberAccess("Url.*");
inputs.Add(temp.FindByMemberAccess("Url.AbsolutePath"));
inputs.Add(temp.FindByMemberAccess("Url.Authority"));
inputs.Add(temp.FindByMemberAccess("Url.DnsSafeHost"));
inputs.Add(temp.FindByMemberAccess("Url.Host"));
inputs.Add(temp.FindByMemberAccess("Url.HostNameType"));
inputs.Add(temp.FindByMemberAccess("Url.IsAbsoluteUri"));
inputs.Add(temp.FindByMemberAccess("Url.IsDefaultPort"));
inputs.Add(temp.FindByMemberAccess("Url.IsFile"));
inputs.Add(temp.FindByMemberAccess("Url.IsLoopback"));
inputs.Add(temp.FindByMemberAccess("Url.IsLoopback"));
inputs.Add(temp.FindByMemberAccess("Url.IsUnc"));
inputs.Add(temp.FindByMemberAccess("Url.LocalPath"));
inputs.Add(temp.FindByMemberAccess("Url.Port"));
inputs.Add(temp.FindByMemberAccess("Url.Scheme"));
inputs.Add(temp.FindByMemberAccess("Url.UserEscaped"));

result.Add(inputs);
result.Add(inputs.GetTargetOfMembers());