List<string> onEventNames = new List<string> {
		"onabort",
		"onactivate",
		"onafterprint",
		"onafterupdate",
		"onbeforeactivate",
		"onbeforecopy",
		"onbeforecut",
		"onbeforedeactivate",
		"onbeforeeditfocus",
		"onbeforeonload",
		"onbeforepaste",
		"onbeforeprint",
		"onbeforeunload",
		"onbeforeupdate",
		"onblur",
		"onbounce",
		"oncanplay",
		"oncanplaythrough",
		"oncellchange",
		"onchange",
		"onclick",
		"oncontextmenu",
		"oncontrolselect",
		"oncopy",
		"oncuechange",
		"oncut",
		"ondataavailable",
		"ondatasetchanged",
		"ondatasetcomplete",
		"ondblclick",
		"ondeactivate",
		"ondrag",
		"ondragend",
		"ondragenter",
		"ondragleave",
		"ondragover",
		"ondragstart",
		"ondrop",
		"ondurationchange",
		"onemptied",
		"onended",
		"onerror",
		"onerrorupdate",
		"onfilterchange",
		"onfinish",
		"onfocus",
		"onfocusin",
		"onfocusout",
		"onformchange",
		"onforminput",
		"onhaschange",
		"onhashchange",
		"onhelp",
		"oninput",
		"oninvalid",
		"onkeydown",
		"onkeypress",
		"onkeyup",
		"onload",
		"onloadeddata",
		"onloadedmetadata",
		"onloadstart",
		"onlosecapture",
		"onmessage",
		"onmousedown",
		"onmouseenter",
		"onmouseleave",
		"onmousemove",
		"onmouseout",
		"onmouseover",
		"onmouseup",
		"onmousewheel", 		// Note: onmousewheel is deprecated, use onwheel instead.
		"onmove",
		"onmoveend",
		"onmovestart",
		"onoffline",
		"onoine",
		"ononline",
		"onpagehide",
		"onpageshow",
		"onpaste",
		"onpause",
		"onplay",
		"onplaying",
		"onpopstate",
		"onprogress",
		"onpropertychange",
		"onratechange",
		"onreadystatechange",
		"onredo",
		"onreset",
		"onresize",
		"onresizeend",
		"onresizestart",
		"onrowenter",
		"onrowexit",
		"onrowsdelete",
		"onrowsinserted",
		"onscroll",
		"onsearch",
		"onseeked",
		"onseeking",
		"onselect",
		"onselectionchange",
		"onselectstart",
		"onshow",
		"onstalled",
		"onstart",
		"onstop",
		"onstorage",
		"onsubmit",
		"onsuspend",
		"ontimeupdate",
		"ontoggle",
		"onundo",
		"onunload",
		"onvolumechange",
		"onwaiting",
		"onwheel"
};

List<string> eventNames = new List<string> {
		"abort",
		"canplay",
		"canplaythrough",
		"durationchange",
		"emptied",
		"ended",
		"error",
		"formaction",
		"loadeddata",
		"loadedmetadata",
		"loadstart",
		"offline",
		"pause",
		"play",
		"playing",
		"poster",
		"progress",
		"ratechange",
		"seeked",
		"seeking",
		"stalled",
		"suspend",
		"timeupdate",
		"volumechange",
		"waiting"
};

// create list with star in the end
List<string> starredEventNames = new List<string>();
starredEventNames.AddRange(eventNames);
foreach(string eventName in eventNames) 
{
	starredEventNames.Add(eventName + "_*"); 
}

List<string> starredOnEventNames = new List<string>();
starredOnEventNames.AddRange(onEventNames);
foreach(string onEventName in onEventNames) 
{
	starredOnEventNames.Add(onEventName + "_*"); 
}

CxList events = All.NewCxList();
events.Add(Find_Methods(), Find_MethodDecls());
events.Add(Find_String_Literal().GetByAncs(Find_Parameters()));

result.Add(events.FindByShortNames(starredEventNames, true));
result.Add(events.FindByShortNames(starredOnEventNames, false));