CxList write = All.FindByMemberAccess("StreamWriter.Write*", false);
write.Add(All.FindByMemberAccess("StreamWriter.Write*", false));
write.Add(All.FindByMemberAccess("BinaryWriter.Write*", false));
write.Add(All.FindByMemberAccess("BufferedStream.Write*", false));
write.Add(All.FindByMemberAccess("FileStream.Write*", false));
write.Add(All.FindByMemberAccess("MemoryStream.Write*", false));
write.Add(All.FindByMemberAccess("Stream.Write*", false));
write.Add(All.FindByMemberAccess("StreamWriter.Write*", false));
write.Add(All.FindByMemberAccess("StringWriter.Write*", false));
write.Add(All.FindByMemberAccess("TextWriter.Write*", false));
result = write;