CxList temp = All.FindByMemberAccess("Request.*", false);
CxList inputs = temp.FindByMemberAccess("Request.UserHostName", false);
inputs.Add(temp.FindByMemberAccess("Request.Filter", false)); 
inputs.Add(temp.FindByMemberAccess("Request.UserHostAddress", false)); 
inputs.Add(temp.FindByMemberAccess("Request.FilePath", false)); 
inputs.Add(temp.FindByMemberAccess("Request.ContentEncoding", false)); 
inputs.Add(temp.FindByMemberAccess("Request.ContentType", false)); 
inputs.Add(temp.FindByMemberAccess("Request.AcceptTypes", false)); 
inputs.Add(temp.FindByMemberAccess("Request.ApplicationPath", false)); 
inputs.Add(temp.FindByMemberAccess("Request.AppRelativeCurrentExecutionFilePath", false)); 
inputs.Add(temp.FindByMemberAccess("Request.CurrentExecutionFilePath", false)); 
inputs.Add(temp.FindByMemberAccess("Request.GetHashCode", false)); 
inputs.Add(temp.FindByMemberAccess("Request.GetType", false)); 
inputs.Add(temp.FindByMemberAccess("Request.HttpMethod", false)); 
inputs.Add(temp.FindByMemberAccess("Request.IsAuthenticated", false)); 	
inputs.Add(temp.FindByMemberAccess("Request.IsLocal", false)); 
inputs.Add(temp.FindByMemberAccess("Request.IsSecureConnection", false)); 
inputs.Add(temp.FindByMemberAccess("Request.LogonUserIdentity", false)); 
inputs.Add(temp.FindByMemberAccess("Request.MapPath", false)); 
inputs.Add(temp.FindByMemberAccess("Request.PhysicalApplicationPath", false)); 
inputs.Add(temp.FindByMemberAccess("Request.RequestType", false)); 
inputs.Add(temp.FindByMemberAccess("Request.ServerVariables", false)); 
inputs.Add(temp.FindByMemberAccess("Request.ValidateInput", false));

result = inputs;
result.Add(inputs.GetTargetOfMembers());